- src/main/java/no/sikt/nva/BrageProcessor.java
- src/main/java/no/sikt/nva/model/dublincore/DcValue.java
- src/main/java/no/sikt/nva/model/record/Record.java
- src/main/java/no/sikt/nva/scrapers/DublinCoreScraper.java
- src/main/java/no/sikt/nva/scrapers/HandleScraper.java
- src/test/java/no/sikt/nva/scrapers/DublinCoreScraperTest.java
> Np 16054 add type to title

- build.gradle
- src/main/java/no/sikt/nva/BrageProcessor.java
- src/main/java/no/sikt/nva/exceptions/ContentException.java
- src/main/java/no/sikt/nva/model/content/ContentFile.java
- src/main/java/no/sikt/nva/model/content/ResourceContent.java
- src/main/java/no/sikt/nva/model/dublincore/DcValue.java
- src/main/java/no/sikt/nva/model/record/Record.java
- src/main/java/no/sikt/nva/scrapers/ContentScraper.java
- src/test/java/no/sikt/nva/ResourceNameConstants.java
- src/test/java/no/sikt/nva/scrapers/ContentScraperTest.java
- src/test/resources/contents
> Np 16233 les zip filer fra contents

- src/main/java/no/sikt/nva/scrapers/TypeMapper.java
- src/test/java/no/sikt/nva/scrapers/TypeMapperTest.java
> Np more types

- src/main/java/no/sikt/nva/model/content/ResourceContent.java
- src/main/java/no/sikt/nva/scrapers/ContentScraper.java
more bugfix than implementation
> NP-17388-more-licenses, bugfix

- src/main/java/no/sikt/nva/BrageMigrationCommand.java
- src/main/java/no/sikt/nva/BrageProcessor.java
- src/main/java/no/sikt/nva/RecordsWriter.java
- src/main/java/no/sikt/nva/model/ErrorDetails.java
- src/main/java/no/sikt/nva/model/WarningDetails.java
- src/main/java/no/sikt/nva/model/record/License.java
- src/main/java/no/sikt/nva/model/record/Record.java
- src/main/java/no/sikt/nva/scrapers/DublinCoreScraper.java
- src/main/java/no/sikt/nva/validators/BrageProcessorValidator.java
- src/main/java/no/sikt/nva/validators/DublinCoreValidator.java
- src/test/java/no/sikt/nva/scrapers/DublinCoreScraperTest.java
- all data is scraped
- added errors and warning to record object
- created counter
> Np 17556 scrape when error

- src/main/java/no/sikt/nva/validators/DoiValidator.java
- src/test/java/no/sikt/nva/validators/DoiValidatorTest.java
> NP-17156-skip-empty-doi, skip empty doi implemented

- src/main/java/no/sikt/nva/model/dublincore/DcValue.java
- src/main/java/no/sikt/nva/model/record/EntityDescription.java
- src/main/java/no/sikt/nva/model/record/Identity.java
- src/main/java/no/sikt/nva/model/record/PublicationInstance.java
- src/main/java/no/sikt/nva/scrapers/EntityDescriptionExtractor.java
- articleNumber scraped as a part of PublicationInstance object
- removed unnecessary @JacocoGenerated tags
> NP-17640-scrape-articleNumber, articleNumber scraped

- src/main/java/no/sikt/nva/model/dublincore/DcValue.java
- src/main/java/no/sikt/nva/scrapers/DublinCoreScraper.java
- Relation Uri is added to ingoredValues in DublinCoreScraper
> NP-17861-ignore-relation-uri, uri ignored

- src/main/java/no/sikt/nva/model/content/ResourceContent.java
- src/main/java/no/sikt/nva/scrapers/ContentScraper.java
- src/test/java/no/sikt/nva/scrapers/ContentScraperTest.java
- Ignored known bundleTypes
- removed unnecessary files from scraping
> NP-ignore-bundles, known bundles ignored

- src/main/java/no/sikt/nva/scrapers/DublinCoreScraper.java
- src/main/java/no/sikt/nva/validators/DublinCoreValidator.java
- src/test/java/no/sikt/nva/scrapers/DublinCoreScraperTest.java
- Added new value to map version/publisherAuthority against.
- Tenker jeg lagger en mapper om det kommer flere verdier etter hvert
> NP-18101-description-version-update, new map value added

- src/main/java/no/sikt/nva/BrageMigrationCommand.java
- src/main/java/no/sikt/nva/BrageProcessor.java
- src/main/java/no/sikt/nva/EmbargoScraper.java
- src/main/java/no/sikt/nva/model/dublincore/DcValue.java
- src/main/java/no/sikt/nva/scrapers/DublinCoreScraper.java
- src/main/java/no/sikt/nva/scrapers/EntityDescriptionExtractor.java
- src/main/java/no/sikt/nva/scrapers/PublisherMapper.java
- description.embargo is scraped + ingored + logged
- commented out values in PublisherMapper
- støtte for flere verdier for partOfSeries, mapper den første 
- extended delimiter for publicationDate
> NP-22871-small-tasks, implemented

- post-to-aws/src/main/java/no/sikt/nva/brage/migration/aws/S3StorageImpl.java
- src/main/java/no/sikt/nva/BrageMigrationCommand.java
- src/main/java/no/sikt/nva/EmbargoScraper.java
- src/test/java/no/sikt/nva/EmbargoScraperTest.java
- src/test/resources/FileEmbargoV2.txt
Lagt til støtte for stolpe "|" i embargo fila + testet at publikasjonen faktisk får med seg embargoen
> NP-25569-test-embargo, embargo

- brage-migration-common/src/main/java/no/sikt/nva/brage/migration/common/model/BrageType.java
- post-to-aws/src/test/java/S3StorageImplTest.java
- src/main/java/no/sikt/nva/BrageMigrationCommand.java
- src/main/java/no/sikt/nva/model/dublincore/DcValue.java
- src/main/java/no/sikt/nva/model/dublincore/Qualifier.java
- src/main/java/no/sikt/nva/scrapers/ContentScraper.java
- src/main/java/no/sikt/nva/scrapers/DublinCoreScraper.java
- src/main/java/no/sikt/nva/scrapers/TypeTranslator.java
- src/main/java/no/sikt/nva/validators/DublinCoreValidator.java
- src/test/java/no/sikt/nva/scrapers/DublinCoreScraperTest.java
- Many small task implemented
+ [publishedVersion, Tidsskriftartikkel, Peer reviewed, Journal article]] https://hdl.handle.net/10037/18469 
+ <dcValue element="identifier">FRIDAID 1140733</dcValue>
+ Munin: Scraping has failed: java.lang.NullPointerException Bundle location: 109/70, Handle: https://hdl.handle.net/10037/3945
+ could not parse content file Bundle location: 197/55, Handle: https://hdl.handle.net/10037/2821 
+ Could not extract contributorsno.sikt.nva.exceptions.ContributorExtractorException: Could not extract contributors
> Np 30875 multiple languages types

- src/main/java/no/sikt/nva/scrapers/EntityDescriptionExtractor.java
Skal håndtere slike tilfeller: Fiskerirettlederen i Vikna, Nærøy og Leka 
Dvs. der "switching" ikke gir mening
> NP-31044-do-not-switch-names-containing-og, implemented

- src/main/java/no/sikt/nva/BrageProcessor.java
mistake fix from previous pull request.
> bug-fix-with-dublicate-error-lig

- src/main/java/no/sikt/nva/channelregister/ChannelRegister.java
- src/main/java/no/sikt/nva/scrapers/DublinCoreScraper.java
- src/main/java/no/sikt/nva/scrapers/EntityDescriptionExtractor.java
- src/main/java/no/sikt/nva/validators/DublinCoreValidator.java
- src/test/java/no/sikt/nva/scrapers/DublinCoreScraperTest.java
- src/test/java/no/sikt/nva/validators/DublinCoreValidatorTest.java
FFI has agreed to map posts without type as Report Other.
> mapping posts without type as report for ffi

- post-to-aws/src/main/java/no/sikt/nva/brage/migration/aws/S3StorageImpl.java
- post-to-aws/src/test/java/S3StorageImplTest.java
Fixing NullPointerException thrown when ContentBundle is null.
> fixing brage errors

- src/main/java/no/sikt/nva/BrageMigrationCommand.java
Loggin samlingsfil that has been read and collections it proceeds
> adding more log messages

- build.gradle
- src/main/java/no/sikt/nva/scrapers/AffiliationsScraper.java
- src/main/java/no/sikt/nva/scrapers/ResourceOwnerMapper.java
- src/test/java/no/sikt/nva/scrapers/AffiliationsScraperTest.java
Throwing exception when can not read affiliations.txt file. 
Adding encoding detector when reading affiliations.txt as string
> adding  exception when can not read affiliation

- src/main/java/no/sikt/nva/scrapers/embargo/OnlineEmbargoCheckerImpl.java
- src/test/java/no/sikt/nva/scrapers/embargo/EmbargoScraperTest.java
Online check with NVA UriWrapper encodes spaces to "+" which as far as I know, correct.
However Brage wants %20 instead, and what Brage wants, Brage gets.
> online-check-encodes-spaces-of-filenames

- brage-migration-common/src/main/java/no/sikt/nva/brage/migration/common/model/record/PublisherVersion.java
- src/main/java/no/sikt/nva/scrapers/DublinCoreScraper.java
- src/main/java/no/sikt/nva/validators/DublinCoreValidator.java
- src/test/java/no/sikt/nva/scrapers/DublinCoreScraperTest.java
Har pratet med Terje. Alt som ikke er akseptert versjon skal mappes mot publisert versjon i NVA. 
Dersom flere versjoner i Brage -> mappes til publisert dersom ingen av de versjonene er aksepterte.
> scraping other version

- src/main/java/no/sikt/nva/BrageMigrationCommand.java
This PR adds support for two custom AWS profiles to facilitate running migrations for an unlimited period of time in the TEST and PROD environments.
Previously, the AWS credentials used by the application were determined by the default profile or the AWS_PROFILE environment variable. With this change, the application can use the nva-test-brage-migration and nva-prod-brage-migration profiles, which should be defined in the user's AWS credentials file.
To use a specific profile, you can set the AWS_PROFILE environment variable before running the application, like so:
`AWS_PROFILE=nva-test-brage-migration /etc/alternatives/jre_11/bin/java -jar nva-brage-migration-1.2-all.jar -c customer -O /brageexports/customer/ -b -j test `
When using ensure that the specified profiles exist in your AWS …
> adding two custom profiles

- brage-migration-common/src/main/java/no/sikt/nva/brage/migration/common/model/record/EntityDescription.java
- brage-migration-common/src/main/java/no/sikt/nva/brage/migration/common/model/record/Record.java
- src/main/java/no/sikt/nva/BrageMigrationCommand.java
- src/main/java/no/sikt/nva/scrapers/DublinCoreScraper.java
- src/main/java/no/sikt/nva/scrapers/EntityDescriptionExtractor.java
- src/main/java/no/sikt/nva/scrapers/SubjectScraper.java
- src/test/java/no/sikt/nva/scrapers/DublinCoreScraperTest.java
Attempting to migrate things in the same order as in Brage gui
> changing all sets to lists

- brage-migration-common/src/main/java/no/sikt/nva/brage/migration/common/model/record/content/ResourceContent.java
- post-to-aws/src/test/java/S3StorageImplTest.java
- src/main/java/no/sikt/nva/scrapers/ContentScraper.java
- src/test/java/no/sikt/nva/scrapers/ContentScraperTest.java
- Persisting dublin_core.xml as record file to S3.
- Refactoring tests a bit. 
Further plan is to store dublin_core.xml as AdministrativeAgreement in NVA.
> persisting dublin_core.xml as associatedArtifact

- src/main/java/no/sikt/nva/BrageMigrationCommand.java
Lagt til disse feltene i credentials fila.
> NP-46969-no-time-limit-upload-to-sandbox-and-dev

- src/main/java/no/sikt/nva/channelregister/ChannelRegister.java
- src/main/java/no/sikt/nva/scrapers/CustomerMapper.java
- src/main/resources/customer_address.csv
Klarer du å huske flere plasser vi må legge inn noe mapping mellom kunde og "spesial filer"
> NP-47168-add-omsorgsforskning

- src/main/java/no/sikt/nva/scrapers/BrageNvaLanguageMapper.java
- src/test/java/no/sikt/nva/scrapers/DublinCoreScraperTest.java
Fikk epost fra samas arkivet og de har sett over at alle poster med "smi" skal være "sme"
> map-sami-smi-to-sme

- src/main/java/no/sikt/nva/scrapers/embargo/OnlineEmbargoCheckerImpl.java
Sølvi åpner disse i en teksteditor og ikke i excel, så da blir det prakk med å åpne lenkene.
> add-space-in-comma-separated-file

- src/main/java/no/sikt/nva/scrapers/EntityDescriptionExtractor.java
- src/test/java/no/sikt/nva/scrapers/DublinCoreScraperTest.java
When multiple titles and some of titles have no values -> use one which is not blank
> filtering out empty main titles

- brage-migration-common/src/main/java/no/sikt/nva/brage/migration/common/model/ErrorDetails.java
- brage-migration-common/src/main/java/no/sikt/nva/brage/migration/common/model/record/FundingSource.java
- brage-migration-common/src/main/java/no/sikt/nva/brage/migration/common/model/record/FundingSources.java
- brage-migration-common/src/main/java/no/sikt/nva/brage/migration/common/model/record/Project.java
- src/main/java/no/sikt/nva/scrapers/DublinCoreScraper.java
- src/main/java/no/sikt/nva/validators/DublinCoreValidator.java
- src/main/resources/funding_sources.json
- src/test/java/no/sikt/nva/scrapers/DublinCoreScraperTest.java
- src/test/java/no/sikt/nva/validators/DublinCoreValidatorTest.java
When extracting project from Brage (which is funding in NVA)
And project name is equal to a name of a funding source from Cristin
Then create project with funding source identifier and name.
> looking up projects in funding sources

- brage-migration-common/src/main/java/no/sikt/nva/brage/migration/common/model/record/Identity.java
- src/main/java/no/sikt/nva/model/dublincore/DcValue.java
- src/main/java/no/sikt/nva/scrapers/DublinCoreScraper.java
- src/main/java/no/sikt/nva/scrapers/EntityDescriptionExtractor.java
- src/test/java/no/sikt/nva/scrapers/EntityDescriptionExtractorTest.java
When importing Brage publication
And Brage publication has only one contributor
And Brage publication has only one orcId
Then create contributor with provided orcId.
> creating contributor with orcId

- src/main/java/no/sikt/nva/scrapers/DublinCoreScraper.java
There are tests for it, main change is that we assume that second part of string is always a serie number
> importing unconfirmed series number as string

- src/main/java/no/sikt/nva/model/dublincore/DcValue.java
- src/test/java/no/sikt/nva/scrapers/DublinCoreScraperTest.java
When scraping xml from brage
And xml element is of type contributor
And xml qualifier is of type department
Then ignore it.
> not importing departments as contributors

- src/main/java/no/sikt/nva/scrapers/EntityDescriptionExtractor.java
- src/test/java/no/sikt/nva/scrapers/DublinCoreScraperTest.java
Removing mapping of version as part of description
> removing mapping of version as description

- src/main/java/no/sikt/nva/scrapers/DublinCoreScraper.java
- src/test/java/no/sikt/nva/scrapers/DublinCoreScraperTest.java
When post from Brage has PartOfSeries, but PartIOfSeries does not mach with any channel from Channel register -> we look it up by issn.
> look up series by issn when part of series is present

- src/main/java/no/sikt/nva/channelregister/ChannelRegister.java
- src/main/java/no/sikt/nva/scrapers/DublinCoreScraper.java
- src/test/java/no/sikt/nva/scrapers/DublinCoreScraperTest.java
Looking up all type of publications from Brage in ChannelRegister. Doing it instead of expanding logic to handle new publication types from different institutions.
> looking up all publications in channel register

- src/main/java/no/sikt/nva/scrapers/EntityDescriptionExtractor.java
- src/main/java/no/sikt/nva/validators/DublinCoreValidator.java
- src/test/java/no/sikt/nva/scrapers/EntityDescriptionExtractorTest.java
Mapping period year to publication date with four digit year.
> mapping publication year from period to four digit year

- src/main/java/no/sikt/nva/BrageProcessor.java
- src/main/java/no/sikt/nva/scrapers/ContentScraper.java
- src/test/java/no/sikt/nva/ResourceNameConstants.java
- src/test/java/no/sikt/nva/scrapers/ContentScraperTest.java
- src/test/resources/uio_contents
UiO wants us to migrate all files for them excepting SWORD. 
Migrating original files as OpenFile (as before)
Migrating all other file types except SWORD as HiddenFile.
> migrating more files for UiO

- src/main/java/no/sikt/nva/channelregister/ChannelRegister.java
- src/main/java/no/sikt/nva/scrapers/DublinCoreScraper.java
- src/test/java/no/sikt/nva/channelregister/ChannelRegisterTest.java
- src/test/java/no/sikt/nva/scrapers/DublinCoreScraperTest.java
Scraping journal from Publisher field when customer is `IMR` and publisher value is `FiskeribladetFiskaren`.
IMR has wrongly registered multiple thousand registrations :)
> scraping journal from publisher field when IMR and FiskeribladetFiskaren
